#!/bin/bash
# Fail fast
#set -o errexit
#set -o nounset
#set -e #don't allow to fail silently

# Installation of Octave packages is dependent on current user.
# This works because postBuild user is the same as user running Binder.
# https://docs.octave.org/interpreter/Administrating-Packages.html
# Use micromamba so that the compilers are properly found.
# micromamba run -n notebook octave-cli --eval 'pkg install -forge symbolic control signal statistics'
# install octave packages does not seem to work great.  worked on mybinder but not on the google deployment

#install phreeqc (doesn't work because need sudo)
#wget http://water.usgs.gov/water-resources/software/PHREEQC/phreeqc-3.7.3-15968.tar.gz
#tar -xf phreeqc-3.7.3-15968.tar.gz
#cd phreeqc-3.7.3-15968
#./configure
#make
#make install #permission denied errors for this.  so move executable.
#instead move the executlable
#mv /home/jovyan/runPHREEQC/phreeqc /srv/conda/bin/phreeqc
#chmod +x /srv/conda/bin/phreeqc

#turn off password and tokens for jupyter
jupyter notebook --generate-config
echo "c.NotebookApp.token = ''" >> /home/jovyan/.jupyter/jupyter_notebook_config.py
echo "c.NotebookApp.password = ''"  >> /home/jovyan/.jupyter/jupyter_notebook_config.py
